
USE customer_db;
SELECT COUNT(*) FROM customer_data;
SELECT * from customer_data limit 10;
DESCRIBE customer_data;

-- Q1. What is the total revenue generated by male vs. female customers
select gender ,sum(purchase_amount) as revenue from customer_data group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount,category from customer_data 
where discount_applied = 'Yes' and purchase_amount >
(select avg(purchase_amount) from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?
select category,item_purchased,  round(avg(review_rating),2) as top_review  from customer_data group by category,item_purchased order by top_review desc limit 5 ;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2) as avg_value from customer_data
where shipping_type in ('Standard','Express') group by shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--     between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_revenue,
sum(purchase_amount) as total_amt
from customer_data group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , round(sum( case when discount_applied ='yes'then 1 else 0 end) *100.0 /count(*),2 ) as discount_percentage
from customer_data group by item_purchased order by discount_percentage desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select 
case
when previous_purchases  <= 5 then 'New'
when previous_purchases between 6 and 10  then 'Returning'
else 'Loyal'
end as customer_segment,
count(*) as total_customer,
round(avg(purchase_amount),2) as aavg_spend
from customer_data group by customer_segment;

-- What are the top 3 most purchased products within each category? 
select item_purchased,category,total_order,rn as rank_produced
from(
select item_purchased,category, count(*) as total_order,
row_number() over (partition by category order by count(*)desc) as rn
from customer_data group by item_purchased,category
) t 
where rn <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer_data where previous_purchases >=5 
 group by subscription_status;
 
 -- Q10. What is the revenue contribution of each age group? 
 select age_group, sum(purchase_amount) as total_rev from customer_data group by age_group
 order by total_rev desc ;







